#!/bin/bash

subnet="172.16"  # Change this to your desired Class B subnet
start_range=1    # Change this to the starting range you want to scan
end_range=255    # Change this to the ending range you want to scan

for host in $(seq $start_range $end_range); do
    ip="$subnet.$host"
    (
        ping -c 1 -w 1 $ip > /dev/null 2>&1
        if [ $? -eq 0 ]; then
            echo "Host $ip is up"
        fi
    ) &
done

# Wait for all background processes to finish
wait
In this script, you specify the Class B subnet in the subnet variable and set the start_range and end_range to define the range of hosts you want to scan within that subnet. This script will scan all hosts within the specified range.

Please note that scanning a large number of hosts may take a considerable amount of time and might generate a lot of network traffic, so use it responsibly and with proper authorization.





