#!/bin/bash

subnet="172.16"  # Change this to your desired Class B subnet
start_range=1    # Change this to the starting range you want to scan
end_range=255    # Change this to the ending range you want to scan

for host in $(seq $start_range $end_range); do
    ip="$subnet.$host"
    (
        ping -c 1 -w 1 $ip > /dev/null 2>&1
        if [ $? -eq 0 ]; then
            echo "Host $ip is up"
        fi
    ) &
done

# Wait for all background processes to finish
wait
