#!/bin/bash

subnet="192.168.1"
range=$(seq 1 254)

for host in $range; do
    ip="$subnet.$host"
    (
        ping -c 1 -w 1 $ip > /dev/null 2>&1
        if [ $? -eq 0 ]; then
            echo "Host $ip is up"
        fi
    ) &
done

# Wait for all background processes to finish
wait
