#!/bin/bash

class_b="192.168"  # Change this to the desired Class B network

for class_c in {0..255}; do
    for host in {1..254}; do
        ip="$class_b.$class_c.$host"
        (
            ping -c 1 -w 1 $ip > /dev/null 2>&1
            if [ $? -eq 0 ]; then
                echo "Host $ip is up"
            fi
        ) &
    done
    # Limit the number of concurrent background processes for better performance
    if ((class_c % 4 == 0)); then
        wait
    fi
done
